### ISSUE TITLE
Use for binary classfication

### ISSUE THREAD

**Issue by o0t1ng0o** [HuXiaoling/imageSeg-2.5D_topo#3]
Hi, @HuXiaoling 
I got some problems about the use for binary classification.
1. Does SLICES_COLLECT means how many class in the classification?
https://github.com/HuXiaoling/imageSeg-3D_topo/blob/01464f17682a2a14f938116d4724dc9002375e8f/modules.py#L35
2. If I have a task for binary classfication, it seems that I need to use this line to calculate the topoloss?
https://github.com/HuXiaoling/imageSeg-3D_topo/blob/01464f17682a2a14f938116d4724dc9002375e8f/modules.py#L140
3. But there is only one channel in my last convolutional layer followed by a sigmoid, I calcualte the nn.BCELoss() for my model. Could you give me a example for this to calculate the topoloss?
Thank you in advance!!

**Comment by HuXiaoling** [comment]
> 1. Does SLICES_COLLECT means how many class in the classification?

Answer: No. This is a 2.5D segmentation framework. SLICES_COLLECT means how many slices you use as input for prediction. If you want to do 2D segmentation, just set SLICES_COLLECT=1. Otherwise it can be 3,5,....

> 2. If I have a task for binary classification, it seems that I need to use this line to calculate the topoloss?

Answer: Yes. And you can refer to [getTopoLoss](https://github.com/HuXiaoling/imageSeg-3D_topo/blob/01464f17682a2a14f938116d4724dc9002375e8f/topoLoss.py#L85).

> 3. But there is only one channel in my last convolutional layer followed by a sigmoid, I calculate the nn.BCELoss() for my model. Could you give me a example for this to calculate the topoloss?

Answer: At present we have two channels, one for 0 and the other for 1. You have two ways to deal with this problem: 1) Modify just a little bit of your architecture to make the output channel = 2. 2) You need to modify the aforementioned 'getTopoLoss' a little bit to calculate the topoloss just for the foreground. The second solution may require you to have a better understanding of the computation of the topoloss.

Hope I make my answers clear. If you still have any questions, please feel free to post them here:)
