### ISSUE TITLE
Unsatisfied output

### ISSUE THREAD

**Issue by SnowBird-13** [HuXiaoling/imageSeg-2.5D_topo#6]
![batch](https://user-images.githubusercontent.com/22191627/95367961-03054f00-0908-11eb-8c40-98c68a15330a.png)
Hello, I use a simple image to test the code as follows,
`persistence_result = cubePers(np.reshape(f_padded, f_padded.size).tolist(), list(f_padded.shape), 0.001)`
And I find the output (only one 1-dimension topology) is not the same as `gudhi.CubicalComplex` (output 3 1-dimension topology).  Are there any bugs in this repository?

By the way, I wonder the meaning of critical points, can you please explain `critical points`  and topology loss can be calculated without critical points?

Look forward to your reply.
Thank you!

**Comment by HuXiaoling** [comment]
Hi @SnowBird-13 ,
> The computation of 0D and 1D Betii number:

For 2D images, we need to consider 1D Betti number: number of holes/handles. 

Take the image you provided (after padding) as an example: There is 1 hole (bounded by black). And 0-dimension Betti number is 3 (set i=0).

I kind of understand your confusion. Actually 0-, 1-dimension Betti numbers are complementary in terms of 2D cases, depending on which you choose as background/foreground. That's why `gudhi.CubicalComplex` outputs different but complementary results.

> meaning of critical points

Critical points correspond to the locations at which the topological changes happen. Topology loss is based on the critical points.

Hope I have made my answers clear enough.

**Comment by SnowBird-13** [comment]
> Hi @SnowBird-13 ,
> 
> > The computation of 0D and 1D Betii number:
> 
> For 2D images, we need to consider 1D Betti number: number of holes/handles.
> 
> Take the image you provided (after padding) as an example: There is 1 hole (bounded by black). And 0-dimension Betti number is 3 (set i=0).
> 
> I kind of understand your confusion. Actually 0-, 1-dimension Betti numbers are complementary in terms of 2D cases, depending on which you choose as background/foreground. That's why `gudhi.CubicalComplex` outputs different but complementary results.
> 
> > meaning of critical points
> 
> Critical points correspond to the locations at which the topological changes happen. Topology loss is based on the critical points.
> 
> Hope I have made my answers clear enough.

Thank you very much for your help!  Could you please share the _**Evaluation metrics**_ code in your paper '**Topology-Preserving Deep Image Segmentation**'

**Comment by HuXiaoling** [comment]
For ARI/VOI python code, please refer to:https://github.com/cremi/cremi_python.

Specially, for ARI: https://github.com/cremi/cremi_python/blob/master/cremi/evaluation/rand.py, for VOI: https://github.com/cremi/cremi_python/blob/master/cremi/evaluation/voi.py

The Betti Error metric is defined by ourselves so I'd like to explain it a bit more. Notes for betti error computation: 

1) In our paper, the betti number is computed based on thresholded sampled patches.
2) We use relative topology to compute betti number. (We add boundary for patches)

**Comment by JiayiChen815** [comment]
Hi @HuXiaoling, could you please explain the meaning of 'thresholded sampled patches'?
