### ISSUE TITLE
error in computing compute_persistence_2DImg_1DHom_lh

### ISSUE THREAD

**Issue by apple629** [HuXiaoling/imageSeg-2.5D_topo#8]
When training, what's wrong with errors like that? 

not scape per:  0.015384615384615385 loss_topo tensor(0., device='cuda:0', grad_fn=<SumBackward0>)
CE: 0.0009232205338776112 Topo: 0.0
row:  0 col:  0
torch.Size([65, 65])
dimension: 2
0 4761
1 9384
2 4624
reduced dimension 2
saved dimension 2
reduced dimension 1
saved dimension 1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Filtration building time = 0 Min
Reduction  time          = 0 Min
@@@@@@@@@@@@@@@@@@@@@@@@@@@@
All calculations computed in 0
Number of errors = 9384
If error happens, please contact the author.
(0,)
  File "topoLoss.py", line 47, in getPers
    pd_lh, bcp_lh, dcp_lh = compute_persistence_2DImg_1DHom_lh(likelihood)
  File "TDFMain_pytorch.py", line 49, in compute_persistence_2DImg_1DHom_lh
    dgm = persistence_result_filtered[:, 1:3]
IndexError: too many indices for array

**Comment by HuXiaoling** [comment]
From your log, it seems that possibly you are trying to compute the persistent diagrams for a pure black/white image/matrix? I mean since we compute the persistent diagrams based on small patches, so possibly you'll come across pure black/white image patches and we should skip these patches. Please refer to here: https://github.com/HuXiaoling/imageSeg-2.5D_topo/blob/master/topoLoss.py#L115

In terms of the topoloss library, I would suggest that you should play with it a little bit before incorporating it into deep frameworks: I mean run the C++ lib with sample images, and try to see what you obtain to have a better understanding of the lib.

**Comment by apple629** [comment]
> From your log, it seems that possibly you are trying to compute the persistent diagrams for a pure black/white image/matrix? I mean since we compute the persistent diagrams based on small patches, so possibly you'll come across pure black/white image patches and we should skip these patches. Please refer to here: https://github.com/HuXiaoling/imageSeg-2.5D_topo/blob/master/topoLoss.py#L115
> 
> In terms of the topoloss library, I would suggest that you should play with it a little bit before incorporating it into deep frameworks: I mean run the C++ lib with sample images, and try to see what you obtain to have a better understanding of the lib.

Thank you so much
